"""empty message

Revision ID: 52ee4b872091
Revises: 9a147a066ac5
Create Date: 2022-06-28 10:06:19.715517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52ee4b872091'
down_revision = '9a147a066ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('name', sa.String(length=50), nullable=True))
    op.drop_constraint('favorites_ibfk_4', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_ibfk_2', 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'character_name')
    op.drop_column('favorites', 'planet_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('planet_name', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('favorites', sa.Column('character_name', mysql.VARCHAR(length=50), nullable=True))
    op.create_foreign_key('favorites_ibfk_2', 'favorites', 'planet', ['planet_name'], ['name'])
    op.create_foreign_key('favorites_ibfk_4', 'favorites', 'character', ['character_name'], ['name'])
    op.drop_column('favorites', 'name')
    # ### end Alembic commands ###
