"""empty message

Revision ID: 5644e8296c86
Revises: efa20cd7be8b
Create Date: 2022-06-26 18:35:59.040258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5644e8296c86'
down_revision = 'efa20cd7be8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('character_id', sa.Integer(), nullable=True))
    op.drop_constraint('favorites_ibfk_1', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'character', ['character_id'], ['id'])
    op.drop_column('favorites', 'character_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('character_name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_ibfk_1', 'favorites', 'character', ['character_name'], ['name'])
    op.drop_column('favorites', 'character_id')
    # ### end Alembic commands ###
